spring:
  rabbitmq:
    host: 123.57.60.147
    port: 5672
    username: ztal
    password: 123456
    virtual-host: learnMq

    listener:
      simple:
#        concurrency: 1
        acknowledge-mode: manual
#        max-concurrency: 1
        retry:
          enabled: true
        prefetch: 1

server:
  port: 8888



